name: conlancer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/brand_identity.png
  - assets/lasso_bg.png
  - assets/product_design.png
  - assets/social_media.png
  - assets/video_production.png
  - assets/web_apps.png
  - assets/whatsapp_ads.png

